language: php
sudo: false
dist: trusty

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

php:
  - 7.2

before_install:
  - composer self-update

install:
  - composer install --no-interaction

script: 
  - php vendor/bin/phpunit
